"""
Build-over-build regression diff.

`pages/<slug>/<timestamp>/` archives every successful run. This script
compares the *current* build with the most recent archived run for the
same slug, emitting `pages/<slug>/<ts>/regression-report.json` and a
short stdout summary.

What it surfaces:
  • per-section drift delta (was 2.1% → now 8.3% — regression)
  • new asset upload failures vs the prior run
  • coverage delta (color/typography globals %)
  • newly-introduced low-confidence sections
  • placement drift (header/footer/popup template counts)

The script is **non-fatal** — its purpose is visibility. The actual gate
remains `verify_quality.py`. Run it after a build to spot "things that
were fine last time and aren't now."

Usage:
    python3 scripts/regression_diff.py --slug home
    python3 scripts/regression_diff.py --slug home --baseline 2026-05-12_18-15-04
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
PAGES = ROOT / "pages"


def _load(p: Path) -> dict:
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        return {}


def _latest_archived_run(slug: str, exclude: Path | None = None) -> Path | None:
    """Return the most recent archived run directory for `slug`, optionally
    skipping `exclude` (used to compare current with previous, not self)."""
    root = PAGES / slug
    if not root.exists():
        return None
    candidates = sorted([p for p in root.iterdir() if p.is_dir()])
    if exclude is not None:
        candidates = [p for p in candidates if p.resolve() != exclude.resolve()]
    return candidates[-1] if candidates else None


def _index_sections_by_name(diff_report: dict) -> dict[str, dict]:
    """{figma_name → section} from a diff/report.json::sections list.

    We key by figma_name (not data_id) because data_id changes every
    write — it's a post-regen Elementor id, regenerated by iterate_data.
    The figma_name is stable across runs as long as the layer isn't
    renamed in Figma.
    """
    out: dict[str, dict] = {}
    for s in (diff_report.get("sections") or []):
        name = s.get("figma_name") or s.get("data_id")
        if name:
            out[name] = s
    return out


def regression_report(slug: str, baseline_run: Path | None = None) -> dict:
    """Compare current `build/` against the previous archived run."""
    current = {
        "diff": _load(BUILD / "diff" / "report.json"),
        "import": _load(BUILD / "import-report.json"),
        "state": _load(BUILD / "state.json"),
    }
    if baseline_run is None:
        baseline_run = _latest_archived_run(slug)
    if baseline_run is None:
        return {"baseline": None, "message": f"No prior archived runs for slug={slug}; nothing to compare."}

    baseline = {
        "diff": _load(baseline_run / "diff" / "report.json"),
        "import": _load(baseline_run / "import-report.json"),
        "state": _load(baseline_run / "state.json"),
    }

    regressions: list[dict] = []
    improvements: list[dict] = []

    # --- 1. Per-section drift delta ---------------------------------------
    cur_secs = _index_sections_by_name(current["diff"])
    base_secs = _index_sections_by_name(baseline["diff"])
    for name, cur in cur_secs.items():
        base = base_secs.get(name)
        if base is None:
            # New section in current — record as info only.
            continue
        cd = cur.get("drift") or 0
        bd = base.get("drift") or 0
        delta = cd - bd
        if delta > 0.03:  # regressed by 3+ percentage points
            regressions.append({
                "kind": "section_drift_regressed",
                "section": name,
                "was": round(bd * 100, 1),
                "now": round(cd * 100, 1),
                "delta_pp": round(delta * 100, 1),
            })
        elif delta < -0.03:
            improvements.append({
                "kind": "section_drift_improved",
                "section": name,
                "was": round(bd * 100, 1),
                "now": round(cd * 100, 1),
                "delta_pp": round(delta * 100, 1),
            })

    # --- 2. Top-line drift delta ------------------------------------------
    cd = current["diff"].get("drift")
    bd = baseline["diff"].get("drift")
    if cd is not None and bd is not None and (cd - bd) > 0.02:
        regressions.append({
            "kind": "overall_drift_regressed",
            "was": round(bd * 100, 2),
            "now": round(cd * 100, 2),
            "delta_pp": round((cd - bd) * 100, 2),
        })

    # --- 3. Coverage delta ------------------------------------------------
    cur_cov = (current["import"].get("global_coverage") or {})
    base_cov = (baseline["import"].get("global_coverage") or {})
    for key in ("colors", "typography"):
        c, b = cur_cov.get(key), base_cov.get(key)
        if isinstance(c, (int, float)) and isinstance(b, (int, float)):
            delta = c - b
            if delta < -0.05:
                regressions.append({
                    "kind": f"coverage_{key}_regressed",
                    "was": round(b * 100, 1),
                    "now": round(c * 100, 1),
                    "delta_pp": round(delta * 100, 1),
                })

    # --- 4. Asset failures appeared -----------------------------------------
    cur_assets = current["import"].get("asset_failures") or []
    base_assets = baseline["import"].get("asset_failures") or []
    if len(cur_assets) > len(base_assets):
        new_failed = [a.get("name") for a in cur_assets if a.get("name") not in {b.get("name") for b in base_assets}]
        regressions.append({
            "kind": "asset_failures_appeared",
            "was": len(base_assets),
            "now": len(cur_assets),
            "new_failed": new_failed[:10],
        })

    # --- 5. Placement drift -----------------------------------------------
    cur_pl = (current["state"].get("placements_summary") or {})
    base_pl = (baseline["state"].get("placements_summary") or {})
    for key in ("header", "footer", "popup"):
        c = cur_pl.get(key, 0) or 0
        b = base_pl.get(key, 0) or 0
        if c < b:
            regressions.append({
                "kind": f"{key}_placement_lost",
                "was": b,
                "now": c,
            })

    try:
        baseline_label = str(baseline_run.relative_to(ROOT))
    except ValueError:
        baseline_label = baseline_run.name
    return {
        "baseline": baseline_label,
        "regressions": regressions,
        "improvements": improvements,
        "verdict": "regressed" if regressions else "ok",
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--slug", required=False, help="Page slug (default: from project-config.json::page_slug)")
    ap.add_argument("--baseline", help="Specific run directory under pages/<slug>/")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    slug = args.slug
    if not slug:
        cfg_path = ROOT / "project-config.json"
        if cfg_path.exists():
            slug = json.loads(cfg_path.read_text()).get("page_slug", "home")
        else:
            slug = "home"

    baseline = None
    if args.baseline:
        cand = PAGES / slug / args.baseline
        if not cand.exists():
            print(f"✗ baseline run not found: {cand}", file=sys.stderr)
            return 2
        baseline = cand

    report = regression_report(slug, baseline)

    if args.json:
        json.dump(report, sys.stdout, indent=2)
        sys.stdout.write("\n")
    else:
        if report.get("baseline") is None:
            print(report["message"])
            return 0
        print(f"Regression diff vs {report['baseline']}:")
        if report["regressions"]:
            print(f"  ✗ {len(report['regressions'])} regression(s):")
            for r in report["regressions"][:10]:
                print(f"    • [{r['kind']}] " + " ".join(
                    f"{k}={v}" for k, v in r.items() if k != "kind"
                ))
            if len(report["regressions"]) > 10:
                print(f"    … + {len(report['regressions']) - 10} more")
        if report["improvements"]:
            print(f"  ✓ {len(report['improvements'])} improvement(s)")

    # Write the report into the current build/ for archival.
    out = BUILD / "regression-report.json"
    out.write_text(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
